language: python
python:
    - 3.8
sudo: false

# safelist
branches:
    only:
    - master
    - dev
    - port2R4

addons:
  apt:
    packages:
      - software-properties-common  
      - libxml2-dev
      - zlib1g-dev
      - libcurl4-openssl-dev
      - wget
      - pandoc

cache:
    directories:
    - $HOME/.local/share/renv
    - $TRAVIS_BUILD_DIR/renv/library

before_install:
    - sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran40/"
    - sudo apt-key adv --keyserver keys.gnupg.net --recv-key 'E298A3A825C0D65DFD57CBB651716619E084DAB9'
    - sudo apt-get update
    - sudo apt install --allow-unauthenticated r-base r-base-dev
    - pip3 --no-cache-dir install -r requirements.txt

install:
    - Rscript -e "install.packages('renv')"
    - Rscript -e "renv::consent(provided=TRUE)"
    - Rscript -e "renv::restore()"
    - Rscript -e 'tinytex::install_tinytex()'
    - python3 --version

script:
    "snakemake all --cores 1"